name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and Test
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: my-nginx-app:latest

      - name: Test Nginx config
        run: docker run --rm my-nginx-app nginx -t