name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    branches: [main]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop and start containers
        run: |
          docker compose down
          docker compose up -d --build

      - name: Verify application accesibility
        run: |
          echo "Waiting for Nginx..."
          for i in {1..10}; do
            if curl -vk https://localhost:443; then
              echo "✅ Nginx is running!"
              exit 0
            fi
            sleep 3
          done
          echo "❌ Nginx failed to start"
          exit 1